import { Link, useParams } from "react-router-dom";

import { usePlan, useProjection } from "../api/hooks";
import { fmtMoney } from "../lib/format";

/**
 * A print-optimised, standalone plan report. "Export PDF" triggers the browser's
 * print dialog (Save as PDF); the @media print rules in index.css strip the app
 * chrome and the on-screen buttons so only this report prints.
 */
export function ReportPage() {
  const { planId } = useParams();
  const id = Number(planId);
  const { data: plan } = usePlan(id);
  const { data, isLoading, error } = useProjection(id);

  if (isLoading) return <p className="muted">Loading report…</p>;
  if (error || !data || !plan)
    return (
      <p style={{ color: "#dc2626" }}>
        Couldn't load report. <Link to={`/plans/${id}`}>Back to plan</Link>
      </p>
    );

  const s = data.summary;
  const generated = new Date().toLocaleDateString("en-IE", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });

  return (
    <div className="report">
      <div className="no-print" style={{ display: "flex", gap: 12, marginBottom: 16 }}>
        <Link to={`/plans/${id}`} className="btn btn-secondary">
          ← Back to plan
        </Link>
        <button className="btn" onClick={() => window.print()}>
          Export PDF
        </button>
      </div>

      <header style={{ borderBottom: "2px solid var(--ink, #1e293b)", paddingBottom: 12, marginBottom: 20 }}>
        <h1 style={{ margin: "0 0 4px" }}>{plan.name}</h1>
        <p className="muted" style={{ margin: 0 }}>
          Financial plan report · base year {plan.base_year} · {plan.projection_years}-year horizon
          · generated {generated}
        </p>
      </header>

      <section style={{ marginBottom: 24 }}>
        <h2 style={{ marginTop: 0 }}>Summary</h2>
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
            gap: 12,
          }}
        >
          <Metric label="Final net worth" value={fmtMoney(s.final_net_worth)} />
          <Metric
            label={`Peak net worth (${s.peak_net_worth_year})`}
            value={fmtMoney(s.peak_net_worth)}
          />
          <Metric label="Lifetime tax" value={fmtMoney(s.total_lifetime_tax)} />
          <Metric
            label="First shortfall"
            value={s.first_shortfall_year === null ? "None" : String(s.first_shortfall_year)}
          />
        </div>
      </section>

      <section>
        <h2>Year by year</h2>
        <p className="muted" style={{ marginTop: 0 }}>All figures in nominal euros.</p>
        <table className="report-table">
          <thead>
            <tr>
              <th>Year</th>
              <th>Gross income</th>
              <th>Total tax</th>
              <th>Net income</th>
              <th>Expenses</th>
              <th>Surplus</th>
              <th>Net worth</th>
              <th>Liquid</th>
            </tr>
          </thead>
          <tbody>
            {data.years.map((y) => (
              <tr key={y.year} className={y.had_shortfall ? "report-shortfall" : undefined}>
                <td>{y.year}</td>
                <td>{fmtMoney(y.gross_income_total)}</td>
                <td>{fmtMoney(y.total_tax)}</td>
                <td>{fmtMoney(y.net_income_total)}</td>
                <td>{fmtMoney(y.expenses_total)}</td>
                <td>{fmtMoney(y.surplus_or_shortfall)}</td>
                <td>{fmtMoney(y.net_worth)}</td>
                <td>{fmtMoney(y.liquid_assets)}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </section>

      <footer className="muted" style={{ marginTop: 24, fontSize: 12 }}>
        Generated by Meridian · Ireland 2026 tax engine. Projections are estimates, not financial
        advice.
      </footer>
    </div>
  );
}

function Metric({ label, value }: { label: string; value: string }) {
  return (
    <div className="report-metric" style={{ border: "1px solid #cbd5e1", borderRadius: 8, padding: 12 }}>
      <div className="muted" style={{ fontSize: 12 }}>
        {label}
      </div>
      <div style={{ fontSize: 20, fontWeight: 600 }}>{value}</div>
    </div>
  );
}
