// Seed payload for the "Try a sample plan" button on PlansList.
// Shape matches the backend export format (services/serialisation.py, format_version 1).
// Lets a first-time user see a populated Let's See in <90s without filling 14 forms.

export function buildSampleHouseholdPayload(): Record<string, unknown> {
  const baseYear = new Date().getFullYear();
  const carlaLocalId = 1;
  const davidLocalId = 2;

  return {
    format_version: 1,
    plan: {
      name: "Sample household — Carla & David",
      base_year: baseYear,
      projection_years: 50,
      tax_config_id: null,
      filing_status: "married",
    },
    people: [
      {
        _local_id: carlaLocalId,
        name: "Carla",
        dob: "1989-04-12",
        is_primary: true,
        life_expectancy: 90,
        gender_for_state_pension: "female",
        retirement_age: 66,
        claims_rent_credit: false,
        lump_sum_pct: 0.25,
        income_sources: [
          {
            kind: "employment",
            name: "Tech salary",
            gross_amount: 78000,
            start_year: baseYear,
            end_year: null,
            escalation_rate: 0.025,
            pays_prsi: true,
            pays_usc: true,
            pension_contribution_pct: 0.08,
            employer_pension_contribution_pct: 0.06,
          },
        ],
      },
      {
        _local_id: davidLocalId,
        name: "David",
        dob: "1987-09-30",
        is_primary: false,
        life_expectancy: 88,
        gender_for_state_pension: "male",
        retirement_age: 66,
        claims_rent_credit: false,
        lump_sum_pct: 0.25,
        income_sources: [
          {
            kind: "employment",
            name: "Pharma salary",
            gross_amount: 65000,
            start_year: baseYear,
            end_year: null,
            escalation_rate: 0.025,
            pays_prsi: true,
            pays_usc: true,
            pension_contribution_pct: 0.05,
            employer_pension_contribution_pct: 0.05,
          },
        ],
      },
    ],
    expenses: [
      {
        name: "Household running costs",
        category: "basic",
        amount: 38000,
        start_year: baseYear,
        end_year: null,
        escalation_rate: 0.02,
      },
      {
        name: "Holidays & lifestyle",
        category: "discretionary",
        amount: 8000,
        start_year: baseYear,
        end_year: null,
        escalation_rate: 0.02,
      },
    ],
    assets: [
      {
        _owner_local_id: null,
        name: "Joint current account",
        kind: "cash",
        value: 18000,
        growth_rate: 0.0,
        cost_basis: 18000,
        acquired_year: baseYear,
        annual_contribution: 0,
        contribution_pct_of_net_income: 0,
        contribution_pct_of_gross_income: 0,
        contribution_start_year: null,
        contribution_end_year: null,
        avc_annual: 0,
        avc_pct_of_gross: 0,
      },
      {
        _owner_local_id: null,
        name: "Family home",
        kind: "property_primary",
        value: 450000,
        growth_rate: 0.03,
        cost_basis: 380000,
        acquired_year: baseYear - 3,
        annual_contribution: 0,
        contribution_pct_of_net_income: 0,
        contribution_pct_of_gross_income: 0,
        contribution_start_year: null,
        contribution_end_year: null,
        avc_annual: 0,
        avc_pct_of_gross: 0,
      },
      {
        _owner_local_id: carlaLocalId,
        name: "Carla — PRSA",
        kind: "prsa",
        value: 42000,
        growth_rate: 0.05,
        cost_basis: 42000,
        acquired_year: baseYear - 5,
        annual_contribution: 0,
        contribution_pct_of_net_income: 0,
        contribution_pct_of_gross_income: 0,
        contribution_start_year: null,
        contribution_end_year: null,
        avc_annual: 0,
        avc_pct_of_gross: 0,
      },
      {
        _owner_local_id: davidLocalId,
        name: "David — Occupational pension",
        kind: "occupational_pension",
        value: 65000,
        growth_rate: 0.05,
        cost_basis: 65000,
        acquired_year: baseYear - 8,
        annual_contribution: 0,
        contribution_pct_of_net_income: 0,
        contribution_pct_of_gross_income: 0,
        contribution_start_year: null,
        contribution_end_year: null,
        avc_annual: 0,
        avc_pct_of_gross: 0,
      },
    ],
    liabilities: [
      {
        name: "Mortgage on family home",
        kind: "mortgage",
        principal: 310000,
        interest_rate: 0.039,
        term_months: 25 * 12,
        start_year: baseYear - 3,
        monthly_payment: 0,
      },
    ],
    goals: [
      {
        _linked_person_local_id: carlaLocalId,
        kind: "retirement",
        name: "Comfortable retirement",
        target_amount: 50000,
        target_year: baseYear + (66 - 36),
        notes: "Target sustainable annual spend in retirement.",
      },
    ],
    scenarios: [],
    bequests: [],
    assumptions: {
      inflation_rate: 0.02,
      default_growth_rate: 0.05,
      property_growth_rate: 0.03,
      earnings_growth: 0.025,
      state_pension_age: 66,
      state_pension_annual_amount: 15_563,
      state_pension_escalation_rate: 0.015,
    },
  };
}
